# Generated by Django 2.2.1 on 2019-05-28 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='consistency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.CharField(max_length=30)),
                ('winner', models.CharField(max_length=30)),
                ('winparty', models.CharField(max_length=30)),
                ('trailer', models.CharField(max_length=30)),
                ('trailparty', models.CharField(max_length=30)),
                ('margin', models.CharField(max_length=30)),
            ],
        ),
    ]
