# Generated by Django 2.2.1 on 2019-05-28 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultSite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consistency',
            new_name='consistencyLS',
        ),
    ]
