# Generated by Django 2.2.1 on 2019-05-29 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultSite', '0002_auto_20190528_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='consistencyAC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.CharField(max_length=30)),
                ('winner', models.CharField(max_length=30)),
                ('winparty', models.CharField(max_length=30)),
                ('trailer', models.CharField(max_length=30)),
                ('trailparty', models.CharField(max_length=30)),
                ('margin', models.CharField(max_length=30)),
                ('district', models.PositiveIntegerField(default=0)),
                ('partycolor', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
