# Generated by Django 2.2.1 on 2019-05-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultSite', '0003_consistencyac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistencyac',
            name='consistency',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='consistencyac',
            name='margin',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='consistencyac',
            name='trailer',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='consistencyac',
            name='trailparty',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='consistencyac',
            name='winner',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='consistencyac',
            name='winparty',
            field=models.CharField(max_length=40),
        ),
    ]
