# Generated by Django 2.2.1 on 2019-05-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultSite', '0005_auto_20190529_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consistencyac',
            name='trailer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='consistencyls',
            name='trailer',
            field=models.CharField(max_length=100),
        ),
    ]
